### ISSUE TITLE
 an error in cv.grpsurv function when  penalty = "gel" or penalty = "cMCP" are used

### ISSUE THREAD

**Issue by tangzx998** [pbreheny/grpreg#12] opened 2017-03-18 05:16 UTC
I am using your R package grpreg (grpregOverlap) to perform survival analysis.

First I chose penalty = "grSCAD",  then run the following code. it looks okay.
  f.over <- grpsurv(x1m, y ,  penalty = "grSCAD" , group = groupvector,  eps=0.005, max.iter=10000)
  cv.over <- cv.grpsurv(x1m, y, nfolds = 10, trace=FALSE, seed=1,  penalty = "grSCAD" , group = groupvector, lambda=f.over$lambda,  eps=0.005, max.iter=10000)

There is no any error, and the output is reasonable.

However, if I set penalty = "gel" or penalty = "cMCP", the following code can run.
   f.over <- grpsurv(x1m, y ,  penalty = "gel" ,    group = groupvector,  eps=0.005, max.iter=10000)
   f.over <- grpsurv(x1m, y ,  penalty = "grSCAD" , group = groupvector,  eps=0.005, max.iter=10000)

but, I can not run cross-validation function, as following:
     cv.over <- cv.grpsurv(x1m, y, nfolds = 10, trace=FALSE, seed=1, penalty = "gel", group = groupvector, lambda=f.over$lambda,  eps=0.005, max.iter=10000)
     cv.over <- cv.grpsurv(x1m, y, nfolds = 10, trace=FALSE, seed=1, penalty = "cMCP", group = groupvector, lambda=f.over$lambda,  eps=0.005, max.iter=10000)
 
the error is:
       Error in reorderGroups(group, group.multiplier, strtrim(penalty, 2) ==  : 
       Length of group.multiplier must equal number of penalized groups

if I remove penalty = "gel" or penalty = "cMCP" from above cv.grpsurv function. there is no error, but the output is unreasonable.
please help me on this problem.

Thanks very much.

Zaixiang Tang
tangzx81@gmail.com

**Comment by pbreheny** [comment] 2017-05-17 20:42
Zaixiang,

Thank you *very* much for bringing this to my attention, and I sincerely apologize for how long it has taken me to get back to you on this.  Unfortunately, 'grpreg' was in the middle of some massive internal changes and not fully functional on the development end when you filed this issue.  However, 'grpreg' is now up and running again, and I believe this issue has been taken care of (as of commit <https://github.com/pbreheny/grpreg/commit/460cd78cdc016beb7e1a3f6d6d7510eda940f496>).  I can't directly test your code because it isn't reproducible, but 'cv.grpsurv' is certainly working with the 'gel' and 'cMCP' penalties.

These changes will be posted to CRAN soon; the new version will be 3.1-0.  If you get a chance to test this out, I would very much appreciate you letting me know if this fixes the bug you were running into.  And again, I really do apologize for the delay in getting back to you on this.

(I'm closing the issue, but let me know if you're still having issues and I'll re-open it)

**Closed as completed by pbreheny** 2017-05-17 20:42 UTC

**Comment by tangzx998** [comment] 2017-05-22 02:35
Hi， Dr.Patrick，
Thanks very much for your response. 
I think you have done very much work on the package. So, it is not late for you reply.
I have used the new version of your package on my data, it looks great. There is no error message now.
Your package is very helpful. I like it very much.
Thanks for your email.
Best Regard.
 
Zaixiang 


___________________________________________________- 
ZaiXiang Tang
PhD, Associate Professor
Department of Epidemiology and Medical Statistics, 
School of Public Health, 
Medical College of Soochow University, China
199 Ren-Ai Road, 
Suzhou Industrial Park, 
Suzhou 215123, Jiangsu Province, China
Tel: +86-512-65883227; 15962215800
Fax: +86-512-65883323
Email: tangzx@suda.edu.cn
 
From: Patrick Breheny
Date: 2017-05-18 04:42
To: pbreheny/grpreg
CC: tangzx998; Author
Subject: Re: [pbreheny/grpreg] an error in cv.grpsurv function when penalty = "gel" or penalty = "cMCP" are used (#12)
Zaixiang,
Thank you very much for bringing this to my attention, and I sincerely apologize for how long it has taken me to get back to you on this. Unfortunately, 'grpreg' was in the middle of some massive internal changes and not fully functional on the development end when you filed this issue. However, 'grpreg' is now up and running again, and I believe this issue has been taken care of (as of commit 460cd78). I can't directly test your code because it isn't reproducible, but 'cv.grpsurv' is certainly working with the 'gel' and 'cMCP' penalties.
These changes will be posted to CRAN soon; the new version will be 3.1-0. If you get a chance to test this out, I would very much appreciate you letting me know if this fixes the bug you were running into. And again, I really do apologize for the delay in getting back to you on this.
(I'm closing the issue, but let me know if you're still having issues and I'll re-open it)
